server:
  mode: dev
  admin:
    addr: 0.0.0.0:8888
    timeout: 15s
  app:
    addr: 0.0.0.0:9000
    timeout: 15s
redis:
  addr: 127.0.0.1:6379
  read-timeout: 4s
  write-timeout: 4s

mysql:
  host: 127.0.0.1:3306
  username: root
  password: 12345678
  database: kts
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 1 # silent, error, warn, info, debug

# 图形验证码配置
Captcha:
  image-width: 240   # 图片宽度
  image-height: 80   # 图片高度
  key-length: 6      # 验证码长度
  expiration: 300s    # 验证码过期时间，单位秒
  period-seconds: 60 # 验证码限制时间，配合max-count使用，单位秒。period-seconds内只能获取max-count次验证码
  max-count: 5     # 验证码在period-seconds时间内最大获取次数
  max-error-count: 3 # 验证码错误次数
  block-duration: 60s # 验证码错误次数超过max-error-count后的封禁时间

Auth:
  issuer: "kts"
  expire-time: 168h # token 过期时间 7天
  buffer-time: 24h  # 刷新 token 的缓冲时间 1d，即 token 过期前 buffer-time 内可以刷新 token，如果在缓存区内利用中间件自动刷新 token
  private-key-file: "./certs/auth.key"  # 私钥
  public-key-file: "./certs/auth.pub"   # 公钥

